### ISSUE TITLE
Build for linux-aarch64

### ISSUE THREAD

**Issue by psarka** [conda-forge/rclone-feedstock#36]
### Comment:

Would love to have a build for linux-aarch64, would it be possible to add it? 🙏

**Comment by psarka** [comment]
Gentle bump :)

If you do not have time for that, would you accept a PR with linux-aarch64 support?

**Comment by luizirber** [comment]
> If you do not have time for that, would you accept a PR with linux-aarch64 support?

Hi @psarka! PR would be welcome, in the [conda-forge-pinning-feedstock repository](https://github.com/conda-forge/conda-forge-pinning-feedstock), according to https://conda-forge.org/docs/maintainer/knowledge_base.html#using-arch-rebuild-txt (need to add rclone to the list)

**Comment by psarka** [comment]
The pinning PR was merged, and I see that an aarch64 build PR was opened. It fails with a strange "too many logs" error, any idea how to fix that?

**Comment by psarka** [comment]
I see you fixed it, thanks!
